CREATE TABLE METODO_TRANSACAO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
)

CREATE TABLE TIPO_TRANSACAO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
)

CREATE TABLE TRANSACAO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	CATEGORIA VARCHAR(100) NOT NULL,
	DATA DATE NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	TIPOTRAN_ID INT,
	METODO_ID INT,
	CONSTRAINT FK_TIPO_TRANSACAO FOREIGN KEY (TIPOTRAN_ID) REFERENCES TIPO_TRANSACAO(ID),
	CONSTRAINT FK_METODO_TRANSACAO FOREIGN KEY (METODO_ID) REFERENCES METODO_TRANSACAO(ID)
)

